### ISSUE TITLE
Storybook fails to load due to scss import error

### ISSUE THREAD

**Issue by chrisllontop** [rhinolabs/rhino-ui#1]
## Description
We're encountering an issue with the Storybook setup for `@rhino-ui/components`, which is preventing us from viewing and interacting with the React component library. The problem seems to be related to how SCSS imports are handled.

## Error Details
When attempting to start Storybook, the process fails. Below is a screenshot of the error message indicating issues with processing a SCSS file import:

<img width="1320" alt="image" src="https://github.com/rhinolabs/rhino-ui/assets/30430879/cc424ae2-069a-46e5-83a0-184e8176583c">

This suggests that the Webpack configuration might be missing an appropriate loader for handling SCSS files, specifically for `@import` statements within SCSS modules.

## Steps to Reproduce
1. Clone the `@rhinolabs/rhino-ui` repository.
2. Install dependencies with `pnpm install`.
3. Run `pnpm run storybook` to start the Storybook development server.
4. The error should be visible in the console output.

## Expected Behavior
Storybook should compile and launch without any errors, allowing for the browsing and testing of the React components within the `@rhinolabs/rhino-ui` library.

## Possible Solutions
A potential solution could involve adjusting the Webpack configuration used by Storybook to ensure it includes a loader capable of processing SCSS files. This might mean adding or fine-tuning loaders such as `sass-loader` to handle `@import` statements within SCSS modules correctly.

## Additional Context
This issue is currently a blocker for the development and testing of components via Storybook. Any help or guidance in resolving this issue would be greatly appreciated.

**Comment by JohnDoe548328** [comment]
I will solve this problem ASAP.I want work with you long term

**Comment by fajarAliM** [comment]
Dear Christian

I am Fajar from Upwork and I've noticed your job post there regarding to this issue.
As I reviewed, I think the issue is because correct loader is not applied to the project for loading SCSS files.

I've already fixed such problems in my past React project, so I am confident that I will fix this problem perfectly in the shortest time.

In my past React project, the problem was because the project was missing 'sass-loader' in package.json and webpack.config.js files. So I've installed the dependency and implemented the proper configuration.

But because your project already has sass-loader as its dependency and some configurations in the webpack.config.js file, I will first check the dependency is installed with correct version and the webpack configuration is working properly for the project.

I think that fix would work for this project, but even if the problem is in other place, I am confident I will quickly identify it and fix it in the shortest time.

My timeline for this issue is between an hour and about 5 hours max.
So if you respond to me on Upwork and send me an offer there, I can start working immediately.

**Comment by Moin105** [comment]
i have forked the project and resolved the issue by using sass live compiler on the project

**Comment by JohnDoe548328** [comment]
ok If you want work with me I will work with you long term

**Comment by gitaumoses4** [comment]
There are two issues here.
1. The scss loader is not picked up by the storybook webpack compiler.
![image](https://github.com/rhinolabs/rhino-ui/assets/25629064/48cc8262-51ce-46c9-9c9c-59af474f88fc)

2. The package `@storybook/instrumenter` is built with .mjs (ES Modules) which is not resolved by the storybook webpack configuration.
![image](https://github.com/rhinolabs/rhino-ui/assets/25629064/e942d98c-b03d-4781-a2c7-7307dc3b13a3)

In order to fix these two issues we need to do the following.

1. Use the @storybook/preset-scss plugin which will automatically load the .scss files for us. (Not that the rules in the `webpack.config.js` file will not be automatically merged with the rules from storybook's webpack config.
2. Install a version of `@storybook/instrumenter` that uses commonjs modules. 


This PR does the proposed fixes: https://github.com/rhinolabs/rhino-ui/pull/9
